version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: simplequeue-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: SimpleQueues
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - simplequeue-network

  # Backend API Server
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: simplequeue-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_DB_URL=mongodb://admin:password123@mongodb:27017/SimpleQueues?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - simplequeue-network

  # Frontend React App
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: simplequeue-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - simplequeue-network

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: simplequeue-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Bangkok
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - backend
      - mongodb
    networks:
      - simplequeue-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: simplequeue-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - n8n
    networks:
      - simplequeue-network

volumes:
  mongodb_data:
    driver: local
  n8n_data:
    driver: local

networks:
  simplequeue-network:
    driver: bridge